version: "3.8"
services:
  # Frontend-backend communication
  www:
    build: 
      context: ./www
    ports:
      - 8080:3000
    networks:
      - public

  # Susbscriptions api
  subscriptions:
    build: 
      context: ./subscriptions
    networks:
      - public
      - private

  # RabbitMQ worker
  mailing:
    build: 
      context: ./mailing
    networks:
      - private

  # RabbitMQ 
  rabbitmq:
    image: rabbitmq:3
    volumes:
      - "./rabbitmq/db:/var/lib/rabbitmq"
    networks:
      - private

volumes:
  rabbitmq:

networks:
  public:
  private:
    internal: true