version: "3.8"
services:
  # Frontend-backend communication
  web:
    build: 
      context: ./www
    ports:
      - "8080:${WEB_PORT}"
    volumes:
      - website-data:/app
    networks:
      - frontend
      - backend

  # Susbscriptions api
  api:
    build: 
      context: ./subscriptions
    networks:
      - backend
      - local

  # RabbitMQ worker
  worker:
    build: 
      context: ./mailing
    networks:
      - local

networks:
  frontend:
  backend:
  local:

volumes:
  website-data:
  api-data:
  worker-data:
  db-data: