version: "3.8"
services:
  # Frontend-backend communication
  www:
    build: 
      context: ./www
    ports:
      - 8080:3000
    networks:
      - public
    restart: always

  # Susbscriptions api
  subscriptions:
    build: 
      context: ./subscriptions
    networks:
      - public
      - private
    restart: always

  # RabbitMQ 
  rabbitmq:
    image: rabbitmq:3
    volumes:
      - "./rabbitmq/db:/var/lib/rabbitmq"
    networks:
      - private
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    restart: always

  # RabbitMQ worker
  mailing:
    build: 
      context: ./mailing
    depends_on:
      - rabbitmq
    networks:
      - private
    restart: always

volumes:
  rabbitmq:

networks:
  public:
  private:
    internal: true